/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "bsblan adapter settings": {
        en: "Adapter settings for bsblan",
        de: "Adaptereinstellungen für bsblan",
        ru: "Настройки адаптера для bsblan",
        pt: "Configurações do adaptador para bsblan",
        nl: "Adapterinstellingen voor bsblan",
        fr: "Paramètres d'adaptateur pour bsblan",
        it: "Impostazioni dell'adattatore per bsblan",
        es: "Ajustes del adaptador para bsblan",
        pl: "Ustawienia adaptera dla bsblan",
        uk: "Налаштування адаптера для bsblan",
        "zh-cn": "bsblan的适配器设置",
    },
};
